app/__init__.py
from flask import Flask
from .site.routes import site
from .api.routes import api
from config import Config
from .authentication.routes import auth

from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from models import db as root_db, login_manager, ma
from flask_cors import CORS
from helpers import JSONEncoder

app = Flask(__name__)
app.debug = True
CORS(app)


app.register_blueprint(site)
app.register_blueprint(auth)
app.register_blueprint(api)

app.json_encoder = JSONEncoder
app.config.from_object(Config)
root_db.init_app(app)
login_manager.init_app(app)
ma.init_app(app)
migrate = Migrate(app, root_db)

app/api/routes.py
from flask import Blueprint, request, jsonify, render_template
import sqlalchemy
from helpers import token_required
from models import db, User, Recipe, Exercise, Log, recipe_schema, recipes_schema, exercise_schema, exercises_schema, log_schema, logs_schema

api = Blueprint('api', __name__, url_prefix='/api')

# RECIPES SECTION
@api.route('/recipes', methods = ['POST'])
@token_required
def create_recipe(current_user_token):
    name = request.json['name']
    meal = request.json['meal']
    ingridients = request.json['ingridients']
    full_recipe = request.json['full_recipe']
    user_token = current_user_token.token  

    recipe = Recipe(name, meal, ingridients, full_recipe, user_token = user_token)

    db.session.add(recipe)
    db.session.commit()
    response = recipe_schema.dump(recipe)
    return jsonify(response)

@api.route('/recipes', methods = ['GET'])
@token_required
def get_recipes(current_user_token):
    a_user = current_user_token.token
    recipes = Recipe.query.filter_by(user_token = a_user).all()
    response = recipes_schema.dump(recipes)
    return jsonify(response)

@api.route('/recipes/<id>', methods = ['GET'])
@token_required
def get_single_recipe(current_user_token, id):
    recipe = Recipe.query.get(id)
    response = recipe_schema.dump(recipe)
    return jsonify(response)

@api.route('/recipes/<id>', methods = ['POST', 'PUT'])
@token_required
def update_recipe(current_user_token, id):
    recipe = Recipe.query.get(id)
    recipe.name = request.json['name']
    recipe.meal = request.json['meal']
    recipe.ingridients = request.json['ingridients']
    recipe.full_recipe = request.json['full_recipe']
    recipe.user_token = current_user_token.token  

    db.session.commit()
    response = recipe_schema.dump(recipe)
    return jsonify(response)


@api.route('/recipes/<id>', methods = ['DELETE'])
@token_required
def delete_recipe(current_user_token, id):
    recipe = Recipe.query.get(id)
    db.session.delete(recipe)
    db.session.commit()
    response = recipe_schema.dump(recipe)
    return jsonify(response)



# EXERCISES SECTION
@api.route('/exercises', methods = ['POST'])
@token_required
def create_exercise(current_user_token):
    name = request.json['name']
    muscle = request.json['muscle']
    type_exercise = request.json['type_exercise']
    difficulty = request.json['difficulty']
    description = request.json['description']
    user_token = current_user_token.token  

    exercise = Exercise(name, muscle, type_exercise, difficulty, description, user_token = user_token)

    db.session.add(exercise)
    db.session.commit()
    response = exercise_schema.dump(exercise)
    return jsonify(response)


@api.route('/exercises', methods = ['GET'])
@token_required
def get_exercises(current_user_token):
    a_user = current_user_token.token
    exercises = Exercise.query.filter_by(user_token = a_user).all()
    response = exercises_schema.dump(exercises)
    return jsonify(response)

@api.route('/exercises/<id>', methods = ['GET'])
@token_required
def get_single_exercise(current_user_token, id):
    exercise = Exercise.query.get(id)
    response = exercise_schema.dump(exercise)
    return jsonify(response)

@api.route('/exercises/<id>', methods = ['POST', 'PUT'])
@token_required
def update_exercise(current_user_token, id):
    exercise = Exercise.query.get(id)
    exercise.name = request.json['name']
    exercise.muscle = request.json['muscle']
    exercise.type_exercise = request.json['type_exercise']
    exercise.difficulty = request.json['difficulty']
    exercise.description = request.json['description']
    exercise.user_token = current_user_token.token  

    db.session.commit()
    response = exercise_schema.dump(exercise)
    return jsonify(response)

@api.route('/exercises/<id>', methods = ['DELETE'])
@token_required
def delete_exercise(current_user_token, id):
    exercise = Exercise.query.get(id)
    db.session.delete(exercise)
    db.session.commit()
    response = exercise_schema.dump(exercise)
    return jsonify(response)

# LOGS SECTION
@api.route('/logs', methods = ['POST'])
@token_required
def create_log(current_user_token):
    date = request.json['date'] 
    weight = request.json['weight']
    sleep = request.json['sleep']
    steps = request.json['steps']
    work_out = request.json['work_out']
    user_token = current_user_token.token  

    log = Log(date, weight, sleep, steps, work_out, user_token = user_token)

    db.session.add(log)
    db.session.commit()
    response = log_schema.dump(log)
    return jsonify(response)

@api.route('/logs', methods = ['GET'])
@token_required
def get_logs(current_user_token):
    a_user = current_user_token.token
    logs = Log.query.filter_by(user_token = a_user).all()
    response = logs_schema.dump(logs)
    return jsonify(response)

@api.route('/logs/<id>', methods = ['GET'])
@token_required
def get_single_log(current_user_token, id):
    log = Log.query.get(id)
    response = log_schema.dump(log)
    return jsonify(response)

@api.route('/logs/<id>', methods = ['POST', 'PUT'])
@token_required
def update_log(current_user_token, id):
    log = Log.query.get(id)
    log.date = request.json['date']
    log.weight = request.json['weight']
    log.sleep = request.json['sleep']
    log.steps = request.json['steps']
    log.work_out = request.json['work_out']
    log.user_token = current_user_token.token  

    db.session.commit()
    response = log_schema.dump(log)
    return jsonify(response)


@api.route('/logs/<id>', methods = ['DELETE'])
@token_required
def delete_log(current_user_token, id):
    log = Log.query.get(id)
    db.session.delete(log)
    db.session.commit()
    response = log_schema.dump(log)
    return jsonify(response)

app/authentication/routes.py
from forms import UserLoginForm
from models import User, db, check_password_hash
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_user, logout_user, LoginManager, current_user, login_required

auth = Blueprint('auth', __name__, template_folder='auth_templates')

@auth.route('/signup', methods = ['GET', 'POST'])
def signup():
    form = UserLoginForm()

    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            print (email, password)

            user = User(email, password = password)

            db.session.add(user)
            db.session.commit()

            flash(f'You have successfully created a user account {email}')
            return redirect(url_for('site.home')) 
    except:
        raise Exception('Invalid form data: Please check your form')
    return render_template('sign_up.html', form = form)

@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    form = UserLoginForm()

    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            
            logged_user = User.query.filter(User.email == email).first()
            if logged_user and check_password_hash(logged_user.password, password):
                login_user(logged_user)
                flash('Successful Login')
                return redirect(url_for('site.profile'))
            else:
                flash("you don't have access to this content", 'auth-failed')
                return redirect(url_for('auth.signin'))
    except:
        raise Exception('Invalid form data: Please check your sign in form')
    return render_template('sign_in.html', form = form)

@auth.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('site.home'))

app/site/routes.py
from flask import Blueprint, render_template

site = Blueprint('site', __name__, template_folder= 'site_templates')

@site.route('/')
def home():
    return render_template('index.html')

@site.route('/profile')
def profile():
    return render_template('profile.html')

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="../static/css/style.css">
<title>Fitness App</title>
</head>
<body>

    <nav class="navbar navbar-expand-lg py-3 fixed-top">
        <div class="container">
            <a href="{{ url_for('site.home')}}" class="navbar-brand">
                Home
            </a>
            <button 
                class="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navmenu"
                ><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navmenu">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
                            <a href="{{ url_for('site.home') }}" class="nav-link">Home</a>
                        </li>
                        {% if current_user.is_authenticated %}
                        <li class="nav-item">
                            <a href="{{ url_for('site.profile') }}" class="nav-link">Profile</a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ url_for('auth.logout') }}" class="nav-link">Logout</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a href="{{ url_for('auth.signin') }}" class="nav-link">Sign In</a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ url_for('auth.signup') }}" class="nav-link">Sign Up</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
        </div>
    </nav>
    
    {% block content %}
    {% endblock %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
</body>
</html>

app/templates/forms.html
<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group mt-3 text-primary">
        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class = 'form-control', placeholder= 'place email here') }}
        </fieldset>
        <fieldset id="password-field">
            {{ form.password.label }}
            {{ form.password(class = 'form-control', placeholder= 'place password here') }}
        </fieldset>

        {{ form.submit_button(class = "btn btn-primary btn-block mt-2") }}
    </div>
</form>